# hermetic run of the full vitest suite. node_modules is vendored from the
# committed bun.nix (generated by bun2nix) so the suite runs offline in the
# nix sandbox, under every runtime in the matrix that supports vitest. exposed
# as packages (not flake checks) so they only build on demand.
{ ... }:
{
  perSystem = { pkgs, lib, runtimeMatrix, mkSuitePackages, ... }:
    let
      # symlink farm recreation of bun's install cache for the whole
      # workspace, built from the committed lockfile expression.
      bunDeps = pkgs.bun2nix.fetchBunDeps {
        bunNix = ../bun.nix;
      };

      vitestRuntimes =
        lib.filterAttrs (_: runtime: runtime.supportsVitest) runtimeMatrix;

      mkVitest = name: runtime:
        pkgs.stdenv.mkDerivation {
          pname = "doba-vitest-${name}";
          version = "0.1.0";
          src = ../.;

          nativeBuildInputs = [ pkgs.bun2nix.hook ];
          inherit bunDeps;

          # the bun2nix hook assembles node_modules in preBuild. we only want
          # that, then run vitest ourselves with the chosen runtime.
          dontRunLifecycleScripts = true;
          dontUseBunBuild = true;
          dontUseBunCheck = true;
          dontUseBunInstall = true;

          buildPhase = ''
            runHook preBuild

            export CI=true
            export NO_COLOR=1
            cd packages/doba

            vitestEntry=""
            for candidate in \
              node_modules/vitest/vitest.mjs \
              ../../node_modules/vitest/vitest.mjs; do
              if [ -f "$candidate" ]; then
                vitestEntry="$candidate"
                break
              fi
            done

            if [ -z "$vitestEntry" ]; then
              echo "could not locate vitest entry in node_modules" >&2
              exit 1
            fi

            echo "running vitest on ${name} via $vitestEntry"

            # a single forked process is deterministic and avoids worker spawn
            # contention when the matrix builds in parallel, which could
            # otherwise let vitest exit 0 without running anything.
            set -o pipefail
            ${runtime.command} "$vitestEntry" run \
              --pool=forks \
              --poolOptions.forks.singleFork=true \
              2>&1 | tee vitest-output.log
            set +o pipefail

            # a run that collects zero tests but still exits 0 must fail the
            # build, otherwise the suite would give false confidence.
            if ! grep -qE "Tests +[1-9][0-9]* passed" vitest-output.log; then
              echo "vitest reported no passing tests on ${name}" >&2
              exit 1
            fi

            cd ../..
            runHook postBuild
          '';

          installPhase = ''
            runHook preInstall
            mkdir -p "$out"
            echo "vitest suite passed on ${name}" > "$out/result"
            runHook postInstall
          '';
        };
    in
    {
      packages = mkSuitePackages {
        prefix = "vitest";
        suites = builtins.mapAttrs mkVitest vitestRuntimes;
      };
    };
}
