/**
 * Generated by tsnapi — public API snapshot of `dobajs`
 */
// #region Interfaces
export interface Matcher {
  (_: unknown): boolean;
  field(_: string, _?: unknown): Matcher;
  fields(..._: string[]): Matcher;
  type(_: string): Matcher;
  test(_: (_: unknown) => boolean): Matcher;
}
export interface PipeBuilder<In, Current, Target = void> {
  (_: In, _: TransformContext): CheckTarget<Current, Target>;
  rename<From$1 extends string & keyof Current, To$1 extends string>(_: From$1, _: To$1): PipeBuilder<In, Simplify<Omit<Current, From$1> & Record<To$1, Current[From$1]>>, Target>;
  add<const Name extends string, const V>(_: Name, _: V): PipeBuilder<In, Simplify<Current & Record<Name, ResolveDefault<V>>>, Target>;
  drop<Names extends string & keyof Current>(..._: Names[]): PipeBuilder<In, Simplify<Omit<Current, Names>>, Target>;
  map<Name extends string & keyof Current, V>(_: Name, _: (_: Current[Name]) => V): PipeBuilder<In, Simplify<Omit<Current, Name> & Record<Name, V>>, Target>;
  into<Target extends Record<string, unknown>>(..._: Exclude<keyof Current, keyof Target> extends never ? [Current] extends [Target] ? [] : [error: "current shape is missing fields from target"] : [error: `extra fields: ${Exclude<keyof Current, keyof Target> & string}`]): (_: In, _: TransformContext) => Target;
}
// #endregion

// #region Types
export type DefaultedInfo<FromKey extends string = string, ToKey extends string = FromKey> = {
  readonly path: readonly PropertyKey[];
  readonly message: string;
  readonly from: FromKey;
  readonly to: ToKey;
};
export type DobaIssue = {
  readonly code: DobaIssueCode;
  readonly message: string;
  readonly path?: readonly PropertyKey[] | undefined;
  readonly meta?: Record<string, unknown> | undefined;
};
export type DobaIssueCode = "validation_failed" | "transform_failed" | "no_path_found" | "unknown_schema" | "invalid_input" | "identify_failed" | "identify_ambiguous";
export type ExplainResult<Keys extends string = string, From$1 extends string = Keys, To$1 extends string = Keys> = {
  readonly from: From$1;
  readonly to: To$1;
  readonly path: readonly Keys[] | null;
  readonly totalCost: number | null;
  readonly steps: readonly ExplainStep<NarrowExclude<Keys, To$1>, NarrowExclude<Keys, From$1>>[];
  readonly summary: string;
};
export type ExplainStep<FromKey extends string = string, ToKey extends string = FromKey> = {
  readonly from: FromKey;
  readonly to: ToKey;
  readonly cost: number;
  readonly label?: string | undefined;
  readonly deprecated?: string | boolean | undefined;
};
export type IdentifyConfig<Keys extends string> = IdentifyGuardMap<Keys> | IdentifyFn;
export type IdentifyFn = (_: unknown) => string | null;
export type IdentifyGuard = (_: unknown) => boolean;
export type IdentifyGuardMap<Keys extends string> = Partial<Readonly<Record<Keys, IdentifyGuard | TryParse>>>;
export type IdentifyMeta<Keys extends string = string> = {
  readonly schema: Keys;
};
export type IdentifyResult<Keys extends string = string> = Result<Keys, readonly DobaIssue[], IdentifyMeta<Keys>>;
export type IdentifyTransformMeta<Keys extends string = string> = TransformMeta<Keys> & {
  readonly from: Keys;
};
export type IdentifyTransformResult<T, Keys extends string = string> = Result<T, readonly DobaIssue[], IdentifyTransformMeta<Keys>>;
export type MigrationDef<FromValue, ToValue, Keys extends string = string, FromKey extends Keys = Keys, ToKey extends Keys = Keys> = MigrationFn<FromValue, ToValue, Keys, FromKey, ToKey> | (MigrationMetadata & {
  readonly migrate: MigrationFn<FromValue, ToValue, Keys, FromKey, ToKey>;
}) | PipeMigrationDef<FromValue, ToValue, Keys, FromKey, ToKey>;
export type MigrationFn<FromValue, ToValue, Keys extends string = string, FromKey extends Keys = Keys, ToKey extends Keys = Keys> = (_: FromValue, _: TransformContext<Keys, FromKey, ToKey>) => ToValue | Promise<ToValue>;
export type MigrationMetadata = {
  readonly deprecated?: string | boolean;
  readonly preferred?: boolean;
  readonly cost?: number;
  readonly label?: string;
};
export type MigrationsFor<Schemas extends SchemaMap> = { [K in PossibleMigrationKeys<SchemaKeys<Schemas>>]?: K extends `${infer From extends SchemaKeys<Schemas>}<->${infer To extends SchemaKeys<Schemas>}` ? ReversibleMigrationDef<InferOutput<Schemas[From]>, InferOutput<Schemas[To]>, SchemaKeys<Schemas>, From, To> : K extends `${infer From extends SchemaKeys<Schemas>}->${infer To extends SchemaKeys<Schemas>}` ? MigrationDef<InferOutput<Schemas[From]>, InferOutput<Schemas[To]>, SchemaKeys<Schemas>, From, To> : never };
export type NarrowExclude<T extends string, U extends string> = [Exclude<T, U>] extends [never] ? T : Exclude<T, U>;
export type PathStrategy = "direct" | "shortest";
export type PipeMigrationDef<FromValue, ToValue, Keys extends string = string, FromKey extends Keys = Keys, ToKey extends Keys = Keys> = MigrationMetadata & {
  readonly pipe: (_: PipeBuilder<FromValue, FromValue, ToValue>) => MigrationFn<FromValue, ToValue, Keys, FromKey, ToKey>;
};
export type Registry<Schemas extends SchemaMap, HasIdentify extends boolean = false> = RegistryBase<Schemas> & (HasIdentify extends true ? RegistryIdentify<Schemas> : unknown);
export type RegistryConfig<Schemas extends SchemaMap> = {
  readonly schemas: Schemas;
  readonly migrations: MigrationsFor<Schemas>;
  readonly pathStrategy?: PathStrategy | undefined;
  readonly hooks?: RegistryHooks<SchemaKeys<Schemas>> | undefined;
  readonly debug?: boolean | undefined;
  readonly identify?: IdentifyConfig<SchemaKeys<Schemas>> | undefined;
};
export type RegistryHooks<Keys extends string = string> = {
  readonly onWarning?: ((_: string, _: Keys, _: Keys) => void) | undefined;
  readonly onTransform?: ((_: TransformHookInfo<Keys>) => void) | undefined;
  readonly onStep?: ((_: StepHookInfo<Keys>) => void) | undefined;
};
export type Result<T, E = unknown, M = unknown> = ResultOk<T, M> | ResultErr<E>;
export type ResultErr<E = unknown> = {
  readonly ok: false;
  readonly issues: E;
};
export type ResultOk<T, M = unknown> = {
  readonly ok: true;
  readonly value: T;
  readonly meta: M;
};
export type ReversibleMigrationDef<FromValue, ToValue, Keys extends string = string, FromKey extends Keys = Keys, ToKey extends Keys = Keys> = MigrationMetadata & {
  readonly forward: MigrationFn<FromValue, ToValue, Keys, FromKey, ToKey>;
  readonly backward: MigrationFn<ToValue, FromValue, Keys, ToKey, FromKey>;
};
export type SchemaKeys<Schemas extends SchemaMap> = Extract<keyof Schemas, string>;
export type SchemaMap = Record<string, StandardSchemaV1>;
export type StepHookInfo<Keys extends string = string> = {
  readonly from: Keys;
  readonly to: Keys;
  readonly index: number;
  readonly total: number;
  readonly label?: string | undefined;
  readonly durationMs: number;
  readonly ok: boolean;
};
export type StepInfo<FromKey extends string = string, ToKey extends string = FromKey> = {
  readonly from: FromKey;
  readonly to: ToKey;
  readonly label?: string | undefined;
  readonly deprecated?: string | boolean | undefined;
};
export type TransformContext<Keys extends string = string, From$1 extends Keys = Keys, To$1 extends Keys = Keys> = {
  readonly warn: (_: string) => void;
  readonly defaulted: (_: readonly PropertyKey[], _: string) => void;
  readonly from: From$1;
  readonly to: To$1;
};
export type TransformHookInfo<Keys extends string = string> = {
  readonly from: Keys;
  readonly to: Keys;
  readonly path: readonly Keys[] | null;
  readonly durationMs: number;
  readonly ok: boolean;
};
export type TransformMeta<Keys extends string = string, From$1 extends string = Keys, To$1 extends string = Keys> = {
  readonly path: readonly Keys[];
  readonly steps: readonly StepInfo<NarrowExclude<Keys, To$1>, NarrowExclude<Keys, From$1>>[];
  readonly warnings: readonly WarningInfo<NarrowExclude<Keys, To$1>, NarrowExclude<Keys, From$1>>[];
  readonly defaults: readonly DefaultedInfo<NarrowExclude<Keys, To$1>, NarrowExclude<Keys, From$1>>[];
};
export type TransformOptions<Keys extends string> = {
  readonly path?: readonly Keys[] | undefined;
  readonly pathStrategy?: PathStrategy | undefined;
  readonly validate?: "none" | "end" | "each" | undefined;
  readonly validatePath?: boolean | undefined;
};
export type TransformResult<T, Keys extends string = string, From$1 extends string = Keys, To$1 extends string = Keys> = Result<T, readonly DobaIssue[], TransformMeta<Keys, From$1, To$1>>;
export type ValidateMeta<Key extends string = string> = {
  readonly schema: Key;
};
export type ValidateResult<T, Key extends string = string> = Result<T, readonly DobaIssue[], ValidateMeta<Key>>;
export type WarningInfo<FromKey extends string = string, ToKey extends string = FromKey> = {
  readonly message: string;
  readonly from: FromKey;
  readonly to: ToKey;
};
// #endregion

// #region Functions
export declare function byField(_: string, _?: ByFieldOptions): (_: unknown) => string | null;
export declare function createRegistry<Schemas extends SchemaMap>(_: RegistryConfig<Schemas>): Registry<Schemas, false>;
export declare function firstMatch(..._: readonly ((value: unknown) => string | null)[]): (_: unknown) => string | null;
export declare function pipe<In>(): PipeBuilder<In, In>;
// #endregion

// #region Variables
export declare const match: Matcher;
export declare const tryParse: unique symbol;
// #endregion